### PR TITLE
Improve Backend Engineer challenge

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Comment by mbaechler** [comment]
I would remove this line entirely, we should not have to require tests

**Comment by guizmaii** [comment]
@mbaechler Agreed. I removed it

**Comment by trobert** [comment]
I disagree, I prefer clear expectations

**Comment by guizmaii** [comment]
@trobert @mbaechler I've put my initial proposition back

**Comment by achever1** [comment]
Replace "Write tests" by "Write what matters most in your vision of a good application" ?
When I did the challenge myself I didn't really see what was expected (having smth working ? show innovation ? kafka expertise ? tests ? doc ?). In the end I found that we mostly want to know what kind of developper the candidate is, so I think if we announce an overall expectation like this, he will know better what to focus on and he'll still have to make choices himself between tests, docs, features..

**Comment by strokyl** [comment]
I think it would be a bit of a trap to remove it. But without asking them explicitly, it would say a lot about how the applicant perceive tests importants.
Someone you submit an answer without tests, is probably someone who will suffer/not want to write unit test.
I would personally remove that line

**Comment by trobert** [comment]
It's unfair to me to reject a candidate if he did not write tests and we don't ask for it, even kinda elitist.

> Someone you submit an answer without tests, is probably someone who will suffer/not want to write unit test.
I would personally remove that line

if we clearly state that we value testing, such people won't apply, so that's even better :)

**Comment by strokyl** [comment]
> if we clearly state that we value testing, such people won't apply, so that's even better :)

Ok good point, let's keep the line

> It's unfair to me to reject a candidate if he did not write tests and we don't ask for it, even kinda elitist.

But I don't think it's elitist to expect from a professional developer to write unit tests by himself

**Pull request closed without merging**
